"""create_dashboards_and_widgets_tables

Revision ID: 44433fe9f485
Revises: e683d4e22083
Create Date: 2026-06-27 23:20:28.111212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44433fe9f485'
down_revision: Union[str, Sequence[str], None] = 'e683d4e22083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboards_id'), 'dashboards', ['id'], unique=False)
    op.create_index(op.f('ix_dashboards_organization_id'), 'dashboards', ['organization_id'], unique=False)
    op.create_table('widgets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dashboard_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('LINE', 'BAR', 'PIE', 'KPI', 'TABLE', name='widget_types'), nullable=False),
    sa.Column('query_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_widgets_dashboard_id'), 'widgets', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_widgets_id'), 'widgets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_widgets_id'), table_name='widgets')
    op.drop_index(op.f('ix_widgets_dashboard_id'), table_name='widgets')
    op.drop_table('widgets')
    op.drop_index(op.f('ix_dashboards_organization_id'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_id'), table_name='dashboards')
    op.drop_table('dashboards')
    # ### end Alembic commands ###
