"""create_invitations_table

Revision ID: 4a65b834399f
Revises: 2cce158492d6
Create Date: 2026-06-27 22:20:41.947061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a65b834399f'
down_revision: Union[str, Sequence[str], None] = '2cce158492d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'invitations', 
        'role',
        existing_type=postgresql.ENUM('OWNER', 'ADMIN', 'ANALYST', 'VIEWER', name='userrole'),
        type_=postgresql.ENUM('OWNER', 'ADMIN', 'ANALYST', 'VIEWER', name='user_roles', create_type=False),
        postgresql_using="role::text::user_roles" # <-- Change this to double cast via text
    )
    op.drop_index(op.f('ix_invitations_organization_id'), table_name='invitations')
    op.drop_constraint(op.f('invitations_invited_by_fkey'), 'invitations', type_='foreignkey')
    op.drop_column('invitations', 'invited_by')
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('invited_by', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('invitations_invited_by_fkey'), 'invitations', 'users', ['invited_by'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_invitations_organization_id'), 'invitations', ['organization_id'], unique=False)
    op.alter_column('invitations', 'role',
               existing_type=sa.Enum('OWNER', 'ADMIN', 'ANALYST', 'VIEWER', name='user_roles'),
               type_=postgresql.ENUM('OWNER', 'ADMIN', 'ANALYST', 'VIEWER', name='userrole'),
               existing_nullable=False)
    # ### end Alembic commands ###
