"""create_alerts_and_history_tables

Revision ID: 6bf7992d5cfa
Revises: 44433fe9f485
Create Date: 2026-06-28 08:53:16.205661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bf7992d5cfa'
down_revision: Union[str, Sequence[str], None] = '44433fe9f485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('time_window_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'TRIGGERED', 'RESOLVED', 'MUTED', name='alert_statuses'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_event_name'), 'alert_rules', ['event_name'], unique=False)
    op.create_index(op.f('ix_alert_rules_id'), 'alert_rules', ['id'], unique=False)
    op.create_index(op.f('ix_alert_rules_organization_id'), 'alert_rules', ['organization_id'], unique=False)
    op.create_table('alert_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alert_rule_id', sa.Uuid(), nullable=False),
    sa.Column('triggered_value', sa.Float(), nullable=False),
    sa.Column('status_at_trigger', sa.Enum('ACTIVE', 'TRIGGERED', 'RESOLVED', 'MUTED', name='alert_statuses'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_history_alert_rule_id'), 'alert_history', ['alert_rule_id'], unique=False)
    op.create_index(op.f('ix_alert_history_id'), 'alert_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_history_id'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_alert_rule_id'), table_name='alert_history')
    op.drop_table('alert_history')
    op.drop_index(op.f('ix_alert_rules_organization_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_event_name'), table_name='alert_rules')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
