"""create_invitations_table

Revision ID: e683d4e22083
Revises: 4a65b834399f
Create Date: 2026-06-27 22:58:58.652358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e683d4e22083'
down_revision: Union[str, Sequence[str], None] = '4a65b834399f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.create_index(op.f('ix_invitations_organization_id'), 'invitations', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invitations_organization_id'), table_name='invitations')
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    # ### end Alembic commands ###
